#Supported File Types
# (Open/Libre)office Impress Slides	(.odp)
# Image files	(.jpg .jpeg .png .gif)	
# Video	files   (.mp4 .avi .mov .ogg .wmv .webm)

# Scheduling by Weekday
# Include a weekday in the filename — "Monday schedule.odp", Tuesday intramurals.jpg", etc. — and it plays only that day. Omit a weekday name and it plays every day.

# Time to wait between image slides
ImageSleepTime=6

# File ordering: 
#  - alphabetical 
#  - random
#  - date_newest
#  - date_oldest
ORDER_BY=random
